//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILoveKFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.ACCOUNT_CUSTOMER = new HashSet<ACCOUNT_CUSTOMER>();
            this.CARTs = new HashSet<CART>();
            this.RECEIPTs = new HashSet<RECEIPT>();
        }
    
        public string ID_CUSTOMER { get; set; }
        public string NAME_CUSTOMER { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH_CUSTOMER { get; set; }
        public string ADDRESS_CITY { get; set; }
        public string ADDRESS_DISTRICT { get; set; }
        public string ADDRESS_WARD { get; set; }
        public string ADDRESS_CUSTOMER { get; set; }
        public string PHONE_CUSTOMER { get; set; }
        public string GMAIL { get; set; }
        public string SEX_CUSTOMER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT_CUSTOMER> ACCOUNT_CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART> CARTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT> RECEIPTs { get; set; }
    }
}
