//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILoveKFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_RECEIPT
    {
        public string ID { get; set; }

        public string ID_CUSTOMER {  get; set; }
        public string ID_RECEIPT { get; set; }
        public string ID_PRODUCT { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> COST { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual RECEIPT RECEIPT { get; set; }
    }
}
