//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILoveKFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISCOUNT()
        {
            this.RECEIPTs = new HashSet<RECEIPT>();
        }
    
        public string CODE_DISCOUNT { get; set; }
        public Nullable<int> PERCENT_DISCOUNT { get; set; }
        public Nullable<double> MONEY_DISCOUNT { get; set; }
        public Nullable<System.DateTime> START_DAY { get; set; }
        public Nullable<System.DateTime> END_DAY { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT> RECEIPTs { get; set; }
    }
}
