//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILoveKFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.ACCOUNT_EMPLOYEE = new HashSet<ACCOUNT_EMPLOYEE>();
        }
    
        public string ID_EMPLOYEE { get; set; }
        public string NAME_EMPLOYEE { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH_EMPLOYEE { get; set; }
        public string ADDRESS_EMPLOYEE { get; set; }
        public string PHONE_EMPLOYEE { get; set; }
        public string GMAIL { get; set; }
        public string SEX_EMPLOYEE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT_EMPLOYEE> ACCOUNT_EMPLOYEE { get; set; }
    }
}
