//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILoveKFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.DETAIL_RECEIPT = new HashSet<DETAIL_RECEIPT>();
        }
    
        public string ID_PRODUCT { get; set; }
        public string NAME_PRODUCT { get; set; }
        public Nullable<int> COST { get; set; }
        public string DESCRIBE { get; set; }
        public string IMAGE_PRODUCT { get; set; }
        public string ID_CATEGORY { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_RECEIPT> DETAIL_RECEIPT { get; set; }
    }
}
