//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILoveKFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECEIPT()
        {
            this.DETAIL_RECEIPT = new HashSet<DETAIL_RECEIPT>();
        }
    
        public string ID_RECEIPT { get; set; }
        public string ID_CUSTOMER { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public string STATUS_RECEIPT { get; set; }
        public string CODE_DISCOUNT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_RECEIPT> DETAIL_RECEIPT { get; set; }
        public virtual DISCOUNT DISCOUNT { get; set; }
    }
}
